### ISSUE TITLE
Create wallet button never activates

### ISSUE THREAD

**Issue by smurrah** [Cryptonomic/Deployments#41]
I opened the latest version of the wallet for Tezos.  I selected a file by entering a new file name and selecting a folder on my local computer.  I entered in matching passwords that met the criteria.  I see no error messages.  The 'Create Wallet' button will not activate.  It is greyed out.  I click on it and it does nothing.

**Comment by hancockm** [comment]
I am having the same issue in windows 10 pro

**Comment by shaun19826** [comment]
Are you still having this issue ?
@hancockm Are you trying to restore your wallet on the galleon wallet ?

**Comment by smurrah** [comment]
No. I’m not having problems anymore. Thanks.

**Comment by hancockm** [comment]
Sorry, I figure it out. The password was not long enough.  The error response didn’t change under the password textfield. It isn’t a normal UI validation where an error comes up when you click the button. It just took me a second because it was an unusual UI flow.


Thanks,



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by cfw34683** [comment]
please close this if its fixed

**Comment by hancockm** [comment]
Doesn't smurrah have to close it because he opened it or can i close it? 

>

**Comment by smurrah** [comment]
Thanks for the help on this.  It is working now.
